# Generated by Django 3.2 on 2021-05-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTR',
        ),
        migrations.DeleteModel(
            name='Mlmodel',
        ),
        migrations.DeleteModel(
            name='RF',
        ),
        migrations.DeleteModel(
            name='SVR',
        ),
    ]
