# Generated by Django 3.2 on 2021-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_dtr_mlmodel_rf_svr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='rice_yield',
            field=models.FloatField(null=True),
        ),
    ]
