# Generated by Django 3.2 on 2021-05-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_dtr_mlmodel_rf_svr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTR',
        ),
        migrations.DeleteModel(
            name='Mlmodel',
        ),
        migrations.DeleteModel(
            name='RF',
        ),
        migrations.DeleteModel(
            name='svr',
        ),
    ]
