# Generated by Django 3.2 on 2021-05-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0008_dtr_mlmodel_realvalue_rf_svr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTR',
        ),
        migrations.DeleteModel(
            name='Mlmodel',
        ),
        migrations.DeleteModel(
            name='RealValue',
        ),
        migrations.DeleteModel(
            name='RF',
        ),
        migrations.DeleteModel(
            name='svr',
        ),
    ]
