# Generated by Django 3.2 on 2021-05-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_dtr_lasso_mlmodel_mlr_realvalue_rf_ridge_svr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTR',
        ),
        migrations.DeleteModel(
            name='lasso',
        ),
        migrations.DeleteModel(
            name='Mlmodel',
        ),
        migrations.DeleteModel(
            name='mlr',
        ),
        migrations.DeleteModel(
            name='RealValue',
        ),
        migrations.DeleteModel(
            name='RF',
        ),
        migrations.DeleteModel(
            name='ridge',
        ),
        migrations.DeleteModel(
            name='svr',
        ),
    ]
