# Generated by Django 3.2.4 on 2021-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0014_dtr_lasso_mlmodel_mlr_realvalue_rf_ridge_svr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('rain', models.FloatField()),
                ('area', models.FloatField()),
                ('pred', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Report',
            },
        ),
    ]
