# Generated by Django 3.2.4 on 2021-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0016_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
