# Generated by Django 3.2.4 on 2021-06-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0019_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='which',
            field=models.TextField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
