# Generated by Django 3.2.4 on 2021-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0020_auto_20210613_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
