# Generated by Django 3.2.4 on 2021-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0022_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('which', models.TextField(unique=True)),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('rain', models.FloatField()),
                ('area', models.FloatField()),
                ('pred', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Report',
            },
        ),
    ]
