# Generated by Django 3.2.4 on 2021-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0023_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='month',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
