# Generated by Django 3.2 on 2021-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0009_auto_20210523_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'DTR',
            },
        ),
        migrations.CreateModel(
            name='lasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'lasso',
            },
        ),
        migrations.CreateModel(
            name='Mlmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('pottasium', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('rice_yield', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'MlModel',
            },
        ),
        migrations.CreateModel(
            name='mlr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'mlr',
            },
        ),
        migrations.CreateModel(
            name='RealValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realVal', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'RealValue',
            },
        ),
        migrations.CreateModel(
            name='RF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'RF',
            },
        ),
        migrations.CreateModel(
            name='ridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'ridge',
            },
        ),
        migrations.CreateModel(
            name='svr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'SVR',
            },
        ),
    ]
