# Generated by Django 3.2.4 on 2021-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0015_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
