# Generated by Django 3.2.4 on 2021-06-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0017_alter_report_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
