# Generated by Django 3.2.4 on 2021-06-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0021_report_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
